version: 0.2

# env:
#   variables:
#     JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - apt-get update
      - apt install openjdk-8-jdk
      - apt install ant
  build:
    commands:
      - echo Build started on `date`
      - ant build
  post_build:
    commands:
      - echo Build completed on `date`
