version: 0.2

# env:
#   variables:
#     JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - apt-get update
      - apt-get install -y openjdk-8-jdk
      - apt-get install -y ant
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - ant build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  type: 
  files:
    - build.xml
