version: 0.2


# env:
#   variables:
#     JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - apt-get update
      - wget https://dlcdn.apache.org//ant/binaries/apache-ant-1.10.12-bin.zip
      - apt-get install -y unzip
      - unzip apache-ant-1.10.12-bin.zip
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - ant run
  post_build:
    commands:
      - echo Build completed on `date`

# phases:
#   install:
#     runtime-versions:
#       java: corretto8
#     commands:
# #      - apt-get update -y
# #       - apt-get install -y software-properties-common
# #       - add-apt-repository ppa:openjdk-r/ppa
# #       - apt-get update -y
# #       - apt-get install -y openjdk-8-jdk
# #       - apt-get install -y maven
#   pre_build:
#     commands:
#       - echo Logging in to Amazon ECR...
#   build:
#     commands:
#       - echo Build started on date
#       - echo Building the Docker image...
#       - mvn clean package
#   post_build:
#     commands:
#       - echo Build completed on date
#       - echo Pushing the Docker image...

# artifacts:
#   type: 
#   files:
#     - build.xml
#     - appspec.yml

# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       java: corretto8
#   build:
#     commands:
#       - echo Build started on `date`
#       - mvn test 
#   post_build:
#     commands:
#       - echo Build completed on `date`
#       - mvn package
artifacts:
  files:
    - target/my-app-1.0-SNAPSHOT.jar
    - appspec.yml
  discard-paths: yes
